"""
Strategy constants for BlueHorseshoe.
"""

TREND_PERIOD = 20
STRONG_R2_THRESHOLD = 0.7
WEAK_R2_THRESHOLD = 0.3
MIN_VOLUME_THRESHOLD = 100000
MIN_STOCK_PRICE = 5.0
MAX_STOCK_PRICE = 500.0
STOP_LOSS_FACTOR = 0.97
TAKE_PROFIT_FACTOR = 1.05

EMA_MARGIN_MULTIPLIER = 1.0
VOLUME_MULTIPLIER = 1.0

# Technical Scoring Constants
OVERSOLD_RSI_THRESHOLD_EXTREME = 30
OVERSOLD_RSI_REWARD_EXTREME = -5.0
OVERSOLD_RSI_THRESHOLD_MODERATE = 35
OVERSOLD_RSI_REWARD_MODERATE = -2.0
OVERSOLD_BB_REWARD = -3.0
OVERSOLD_BB_POSITION_THRESHOLD = 0.1

# Mean Reversion Specific (Always positive bonuses)
MR_OVERSOLD_RSI_REWARD_EXTREME = 6.0
MR_OVERSOLD_RSI_REWARD_MODERATE = 3.0
MR_OVERSOLD_BB_REWARD = 4.0
MR_BELLOW_LOW_BB_BONUS = 2.0  # Extra bonus if price is actually below BB Lower
MR_CONFLUENCE_BONUS = 3.0 # Bonus for both RSI and BB oversold

PENALTY_EMA_OVEREXTENSION_MODERATE = -3.0
PENALTY_EMA_OVEREXTENSION_EXTREME = -7.0
PENALTY_EMA_THRESHOLD_MODERATE = 0.07
PENALTY_EMA_THRESHOLD_EXTREME = 0.12

PENALTY_RSI_THRESHOLD_EXTREME = 75
PENALTY_RSI_SCORE_EXTREME = -5.0
PENALTY_RSI_THRESHOLD_MODERATE = 70
PENALTY_RSI_SCORE_MODERATE = -2.0
PENALTY_VOLUME_EXHAUSTION = -3.0

# ATR Timing Optimization Constants
ATR_WINDOW = 14
ATR_MULTIPLIER_UPTREND = 0.5
ATR_MULTIPLIER_DOWNTREND = 1.0

# Reward-to-Risk Filtering
MIN_RR_RATIO = 1.2  # Increased from 1.0

# Volume Confirmation
MIN_REL_VOLUME = 1.0  # Must be at least average volume

# Multi-Timeframe Alignment
REQUIRE_WEEKLY_UPTREND = True
