FROM continuumio/miniconda3:23.3.1-0
ENV PYTHONUNBUFFERED=1
# Set the working directory
WORKDIR /workspaces/BlueHorseshoe

COPY docker/requirements.txt .
RUN yes | conda install -c conda-forge ta-lib
RUN pip3 install -r requirements.txt
ENV PYTHONPATH=${PYTHONPATH}:/workspaces/BlueHorseshoe

EXPOSE 80
EXPOSE 7496

# Keep the container running in an interactive state
CMD ["tail", "-f", "/dev/null"]
