"""
This module contains test functions for the MovingAverageIndicator class.

The module includes tests for various moving average calculations including:
- Weighted Moving Average (WMA)  
- Volume Weighted Moving Average (VWMA)
- Moving Average Score
- Moving Average Crossovers

The tests use sample financial data generated by the sample_data() function
which creates a DataFrame with sequential test data for volume and close prices.

Test Functions:
- test_calculate_wma(): Tests WMA calculation
- test_calculate_vwma(): Tests VWMA calculation  
- test_calculate_ma_score(): Tests MA score calculation
- test_calculate_crossovers(): Tests MA crossover signals
- test_calculate_score(): Tests overall indicator score

Dependencies:
    pandas
    indicators.moving_average_indicators.MovingAverageIndicator
"""

import sys
import pandas as pd
sys.path.append('/workspaces/BlueHorseshoe/src')
from indicators.moving_average_indicators import MovingAverageIndicator # pylint: disable=wrong-import-position

def sample_data():
    """
    Generate sample financial data for testing purposes.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing sequential test data with 'volume' and 'close' columns,
        where both volume and close values range from 1 to 30.
        The data is cast to float type.

    Example
    -------
    >>> df = sample_data()
    >>> df.head()
       volume  close
    0    1.0    1.0
    1    2.0    2.0
    2    3.0    3.0
    3    4.0    4.0
    4    5.0    5.0
    """
    df = pd.DataFrame([
    { 'volume': 1, 'close': 1 },
    { 'volume': 2, 'close': 2 },
    { 'volume': 3, 'close': 3 },
    { 'volume': 4, 'close': 4 },
    { 'volume': 5, 'close': 5 },
    { 'volume': 6, 'close': 6 },
    { 'volume': 7, 'close': 7 },
    { 'volume': 8, 'close': 8 },
    { 'volume': 9, 'close': 9 },
    { 'volume': 10, 'close': 10 },
    { 'volume': 11, 'close': 11 },
    { 'volume': 12, 'close': 12 },
    { 'volume': 13, 'close': 13 },
    { 'volume': 14, 'close': 14 },
    { 'volume': 15, 'close': 15 },
    { 'volume': 16, 'close': 16 },
    { 'volume': 17, 'close': 17 },
    { 'volume': 18, 'close': 18 },
    { 'volume': 19, 'close': 19 },
    { 'volume': 20, 'close': 20 },
    { 'volume': 21, 'close': 21 },
    { 'volume': 22, 'close': 22 },
    { 'volume': 23, 'close': 23 },
    { 'volume': 24, 'close': 24 },
    { 'volume': 25, 'close': 25 },
    { 'volume': 26, 'close': 26 },
    { 'volume': 27, 'close': 27 },
    { 'volume': 28, 'close': 28 },
    { 'volume': 29, 'close': 29 },
    { 'volume': 30, 'close': 30 }
    ])
    return df.astype(float)

def test_calculate_wma():
    """Test the calculation of Weighted Moving Average (WMA).

    This test function verifies that:
    1. The WMA calculation returns a series with the same length as input data
    2. The first 19 values are NaN due to the default window size (20)
    3. The calculation is performed correctly using MovingAverageIndicator class

    Args:
        None

    Returns:
        None

    Example:
        >>> test_calculate_wma()
        # Asserts pass if WMA calculation is correct
    """
    indicator = MovingAverageIndicator(sample_data())
    wma = indicator.calculate_wma()
    assert len(wma) == len(sample_data())
    assert wma.isna().sum() == 19  # First 19 values should be NaN due to window size

def test_calculate_vwma():
    """
    Test the calculation of the Volume Weighted Moving Average (VWMA).

    This test validates that:
    1. The VWMA calculation returns a series with the same length as input data
    2. The initial window size (19) values are NaN as expected
    3. The VWMA is properly calculated using price and volume data

    Parameters
    ----------
    None

    Returns
    -------
    None

    Raises
    ------
    AssertionError
        If the VWMA calculation doesn't match expected behavior
    """
    indicator = MovingAverageIndicator(sample_data())
    vwma = indicator.calculate_vwma()
    assert len(vwma) == len(sample_data())
    assert vwma.isna().sum() == 19  # First 19 values should be NaN due to window size

def test_calculate_ma_score():
    """
    Test the calculation of moving average score.

    This test function verifies that the calculate_ma_score method of
    MovingAverageIndicator class returns a float value when provided
    with sample data.

    Returns:
        None

    Asserts:
        - The returned score is an instance of float
    """
    indicator = MovingAverageIndicator(sample_data())
    score = indicator.calculate_ma_score()
    assert isinstance(score, float)

def test_calculate_crossovers():
    """Tests the calculate_crossovers method of MovingAverageIndicator class.

    Tests whether the calculate_crossovers method correctly identifies crossover
    signals between moving averages and returns a valid signal value.

    Returns:
        None

    Tests:
        - Verifies that the returned crossover signal is either 0.0 or 1.0
    """
    indicator = MovingAverageIndicator(sample_data())
    crossover_signal = indicator.calculate_crossovers()
    assert crossover_signal in [0.0, 1.0]

def test_calculate_score():
    """Tests the calculate_score method of MovingAverageIndicator class.

    Verifies that the calculate_score method returns a float value representing
    the indicator's score based on sample data.

    Returns:
        None

    Raises:
        AssertionError: If the returned score is not a float
    """
    indicator = MovingAverageIndicator(sample_data())
    score = indicator.calculate_score()
    assert isinstance(score, float)
