"""HTML and CSV report rendering for BH FTMO Phase 3 backtest results.

Standalone per decision 15D: this module does not depend on the equity-side
reporting stack. HTML output is self-contained with inline CSS and base64 PNG
charts generated by matplotlib.
"""

from __future__ import annotations

# pylint: disable=too-many-arguments,too-many-locals

import base64
from datetime import UTC, datetime
from html import escape
from io import BytesIO
import json
from pathlib import Path
from typing import Optional

from matplotlib.figure import Figure
import pandas as pd

from bh_ftmo.backtest.metrics import (
    CohortMetrics,
    bootstrap_pass_rate_distribution,
    cohort_metrics,
    equity_metrics,
    per_session_breakdown,
    per_strategy_breakdown,
    trade_metrics,
)
from bh_ftmo.backtest.types import ChallengeResult, Trade


def write_csv_ledger(
    results: dict[str, ChallengeResult],
    output_path: Path,
) -> None:
    """Write a flat per-trade CSV ledger across one or more strategies."""

    rows: list[dict[str, object]] = []
    for strategy_name, result in results.items():
        for trade in result.trades:
            rows.append(_trade_row(strategy_name, trade))

    frame = pd.DataFrame(
        rows,
        columns=[
            "strategy",
            "symbol",
            "direction",
            "open_ts",
            "open_price",
            "close_ts",
            "close_price",
            "stop",
            "target",
            "lots",
            "pnl_account_ccy",
            "swap_account_ccy",
            "commission_account_ccy",
            "exit_reason",
            "components_json",
        ],
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output_path, index=False)


def render_html_report(
    results: dict[str, ChallengeResult],
    output_path: Path,
    *,
    cohort_metrics_by_strategy: Optional[dict[str, CohortMetrics]] = None,
    cohort_results_by_strategy: Optional[dict[str, list[ChallengeResult]]] = None,
    gate_result: Optional[object] = None,
    title: str = "BH FTMO Backtest Report",
    run_id: Optional[str] = None,
) -> None:
    """Render a self-contained HTML report for one or more strategy runs."""

    if not results:
        raise ValueError("results must not be empty")

    resolved_run_id = run_id or _default_run_id(results)
    generated_at = _utc_now_naive()
    normalized_cohort_metrics = _normalize_cohort_metrics(
        cohort_metrics_by_strategy=cohort_metrics_by_strategy,
        cohort_results_by_strategy=cohort_results_by_strategy,
    )

    summary_cards: list[str] = []
    session_sections: list[str] = []
    ledger_sections: list[str] = []
    equity_daily_by_strategy: dict[str, pd.Series] = {}
    equity_metrics_by_strategy: dict[str, object] = {}

    for strategy_name, result in results.items():
        trade_summary = trade_metrics(result)
        equity_summary = equity_metrics(result)
        equity_metrics_by_strategy[strategy_name] = equity_summary
        equity_daily_by_strategy[strategy_name] = result.equity_curve_daily.astype(float)
        cohort_summary = normalized_cohort_metrics.get(strategy_name)
        summary_cards.append(
            _summary_card_html(strategy_name, result, trade_summary, equity_summary, cohort_summary)
        )
        session_sections.append(_session_breakdown_html(strategy_name, result))
        ledger_sections.append(_ledger_preview_html(strategy_name, result.trades))

    overview_chart = _fig_to_data_uri(_equity_curves_figure(equity_daily_by_strategy))
    drawdown_chart = _fig_to_data_uri(_worst_drawdown_figure(results, equity_metrics_by_strategy))
    histogram_section = ""
    if normalized_cohort_metrics:
        histogram_section = _bootstrap_section_html(
            normalized_cohort_metrics,
            cohort_results_by_strategy,
        )

    strategy_breakdown_section = ""
    if len(results) > 1:
        strategy_breakdown_section = _strategy_breakdown_html(list(results.values()))

    gate_section = _gate_section_html(gate_result)

    # TODO(phase-3.5): add per-cluster breakdown once cluster mapping/reporting is wired.
    html = "".join(
        [
            "<!DOCTYPE html>",
            "<html lang=\"en\">",
            "<head>",
            "<meta charset=\"utf-8\">",
            f"<title>{escape(title)}</title>",
            "<style>",
            _STYLE,
            "</style>",
            "</head>",
            "<body>",
            "<div class=\"page\">",
            f"<header><h1>{escape(title)}</h1>",
            f"<p><strong>Run ID:</strong> {escape(resolved_run_id)}</p>",
            f"<p><strong>Generated:</strong> {_format_datetime(generated_at)}</p></header>",
            "<section><h2>Per-Strategy Summary</h2><div class=\"card-grid\">",
            "".join(summary_cards),
            "</div></section>",
            "<section><h2>Equity Curves</h2>",
            f"<img alt=\"Equity curves\" src=\"{overview_chart}\">",
            "</section>",
            "<section><h2>Worst-DD Chain Visualization</h2>",
            f"<img alt=\"Worst drawdown chain\" src=\"{drawdown_chart}\">",
            "</section>",
            histogram_section,
            "<section><h2>Per-Session Breakdown</h2>",
            "".join(session_sections),
            "</section>",
            strategy_breakdown_section,
            gate_section,
            "<section><h2>Trade Ledger Preview</h2>",
            "".join(ledger_sections),
            "</section>",
            "</div></body></html>",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")


def _trade_row(strategy_name: str, trade: Trade) -> dict[str, object]:
    return {
        "strategy": strategy_name,
        "symbol": trade.symbol,
        "direction": trade.direction,
        "open_ts": trade.open_ts.isoformat(sep=" "),
        "open_price": trade.open_price,
        "close_ts": trade.close_ts.isoformat(sep=" "),
        "close_price": trade.close_price,
        "stop": trade.stop,
        "target": trade.target,
        "lots": trade.lots,
        "pnl_account_ccy": trade.pnl_account_ccy,
        "swap_account_ccy": trade.swap_account_ccy,
        "commission_account_ccy": trade.commission_account_ccy,
        "exit_reason": trade.exit_reason,
        "components_json": json.dumps(trade.components, sort_keys=True),
    }


def _summary_card_html(
    strategy_name: str,
    result: ChallengeResult,
    trade_summary: object,
    equity_summary: object,
    cohort_summary: Optional[CohortMetrics],
) -> str:
    rows = [
        ("Outcome", result.outcome),
        ("Trades", str(trade_summary.n_trades)),
        ("Win Rate", _format_pct(trade_summary.win_rate)),
        ("Profit Factor", _format_ratio(trade_summary.profit_factor)),
        ("R Expectancy", _format_ratio(trade_summary.r_expectancy)),
        ("Sharpe (ann.)", _format_ratio(equity_summary.sharpe_annualized)),
        ("Sortino (ann.)", _format_ratio(equity_summary.sortino_annualized)),
        ("Max DD", _format_pct(equity_summary.max_drawdown_pct)),
        ("Max DD (ccy)", _format_ccy(equity_summary.max_drawdown_account_ccy)),
        ("Final Equity", _format_ccy(result.final_equity_account_ccy)),
    ]
    if cohort_summary is not None:
        rows.extend(
            [
                ("Pass Rate", _format_pct(cohort_summary.pass_rate)),
                (
                    "95% CI",
                    f"{_format_pct(cohort_summary.pass_rate_lower_ci_95)} – "
                    f"{_format_pct(cohort_summary.pass_rate_upper_ci_95)}",
                ),
            ]
        )
    return (
        f"<article class=\"card\"><h3>{escape(strategy_name)}</h3>"
        f"{_table_html(['Metric', 'Value'], rows)}</article>"
    )


def _equity_curves_figure(equity_daily_by_strategy: dict[str, pd.Series]) -> Figure:
    fig = Figure(figsize=(10, 4.5))
    axis = fig.add_subplot(111)
    for strategy_name, series in equity_daily_by_strategy.items():
        if series.empty:
            continue
        axis.plot(series.index, series.values, label=strategy_name, linewidth=2)
    axis.set_title("Daily Equity Curves")
    axis.set_xlabel("Time")
    axis.set_ylabel("Equity")
    axis.grid(True, alpha=0.2)
    _, labels = axis.get_legend_handles_labels()
    if labels:
        axis.legend(loc="best")
    fig.autofmt_xdate()
    return fig


def _worst_drawdown_figure(
    results: dict[str, ChallengeResult],
    equity_metrics_by_strategy: dict[str, object],
) -> Figure:
    fig = Figure(figsize=(10, max(4.0, 3.0 * len(results))))
    total = len(results)
    for idx, (strategy_name, result) in enumerate(results.items(), start=1):
        axis = fig.add_subplot(total, 1, idx)
        series = result.equity_curve.astype(float)
        metrics = equity_metrics_by_strategy[strategy_name]
        axis.plot(series.index, series.values, color="#1d3557", linewidth=1.8)
        axis.scatter(
            [metrics.worst_dd_peak_ts, metrics.worst_dd_trough_ts],
            [series.loc[metrics.worst_dd_peak_ts], series.loc[metrics.worst_dd_trough_ts]],
            color=["#2a9d8f", "#e63946"],
            zorder=3,
        )
        if metrics.worst_dd_trade_chain:
            open_times = [trade.open_ts for trade in metrics.worst_dd_trade_chain]
            open_values: list[float] = []
            for trade in metrics.worst_dd_trade_chain:
                nearest = series.index.get_indexer([pd.Timestamp(trade.open_ts)], method="nearest")
                open_values.append(float(series.iloc[int(nearest[0])]))
            axis.scatter(open_times, open_values, color="#f4a261", s=18, alpha=0.9)
        axis.set_title(f"{strategy_name} Worst Drawdown")
        axis.grid(True, alpha=0.2)
    fig.autofmt_xdate()
    return fig


def _bootstrap_section_html(
    cohort_metrics_by_strategy: dict[str, CohortMetrics],
    cohort_results_by_strategy: Optional[dict[str, list[ChallengeResult]]],
) -> str:
    chart = _fig_to_data_uri(
        _bootstrap_histogram_figure(cohort_metrics_by_strategy, cohort_results_by_strategy)
    )
    rows: list[tuple[str, str, str, str, str]] = []
    for strategy_name, metrics in sorted(cohort_metrics_by_strategy.items()):
        rows.append(
            (
                strategy_name,
                _format_pct(metrics.pass_rate),
                _format_pct(metrics.pass_rate_lower_ci_95),
                _format_pct(metrics.pass_rate_upper_ci_95),
                str(metrics.bootstrap_b),
            )
        )
    return (
        "<section><h2>Pass-Rate Bootstrap CI Histogram</h2>"
        f"<img alt=\"Pass-rate bootstrap CI histogram\" src=\"{chart}\">"
        f"{_table_html(['Strategy', 'Pass Rate', 'CI Lower', 'CI Upper', 'B'], rows)}</section>"
    )


def _bootstrap_histogram_figure(
    cohort_metrics_by_strategy: dict[str, CohortMetrics],
    cohort_results_by_strategy: Optional[dict[str, list[ChallengeResult]]],
) -> Figure:
    fig = Figure(figsize=(10, 4.5))
    axis = fig.add_subplot(111)
    palette = ["#1d3557", "#2a9d8f", "#e76f51", "#6a4c93"]
    for idx, (strategy_name, metrics) in enumerate(sorted(cohort_metrics_by_strategy.items())):
        color = palette[idx % len(palette)]
        distribution = []
        if cohort_results_by_strategy and strategy_name in cohort_results_by_strategy:
            distribution = bootstrap_pass_rate_distribution(
                cohort_results_by_strategy[strategy_name],
                bootstrap_b=metrics.bootstrap_b,
                rng_seed=0,
            )
        if len(distribution) > 0:
            axis.hist(distribution, bins=20, density=True, alpha=0.30, color=color, label=strategy_name)
        axis.axvline(metrics.pass_rate, color=color, linestyle="-", linewidth=2)
        axis.axvline(metrics.pass_rate_lower_ci_95, color=color, linestyle="--", linewidth=1.5)
        axis.axvline(metrics.pass_rate_upper_ci_95, color=color, linestyle="--", linewidth=1.5)
    axis.set_title("Bootstrap Pass-Rate Confidence Intervals")
    axis.set_xlabel("Pass rate")
    axis.set_ylabel("Density")
    axis.grid(True, alpha=0.2)
    _, labels = axis.get_legend_handles_labels()
    if labels:
        axis.legend(loc="best")
    return fig


def _session_breakdown_html(strategy_name: str, result: ChallengeResult) -> str:
    breakdown = per_session_breakdown(result)
    rows = [
        (
            session_name,
            str(metrics.n_trades),
            _format_pct(metrics.win_rate),
            _format_ratio(metrics.profit_factor),
            _format_ccy(metrics.total_pnl),
        )
        for session_name, metrics in breakdown.items()
    ]
    return (
        f"<h3>{escape(strategy_name)}</h3>"
        f"{_table_html(['Session', 'Trades', 'Win Rate', 'PF', 'Total PnL'], rows)}"
    )


def _strategy_breakdown_html(results: list[ChallengeResult]) -> str:
    breakdown = per_strategy_breakdown(results)
    rows = [
        (
            strategy_name,
            str(metrics.n_trades),
            _format_pct(metrics.win_rate),
            _format_ratio(metrics.profit_factor),
            _format_ratio(metrics.r_expectancy),
            _format_ccy(metrics.total_pnl),
        )
        for strategy_name, metrics in breakdown.items()
    ]
    return (
        "<section><h2>Per-Strategy Breakdown</h2>"
        f"{_table_html(['Strategy', 'Trades', 'Win Rate', 'PF', 'R Exp', 'Total PnL'], rows)}</section>"
    )


def _gate_section_html(gate_result: Optional[object]) -> str:
    if gate_result is None:
        body = "Gate evaluation not yet run (sub-phase 3.4)."
    else:
        body = escape(str(gate_result))
    return f"<section><h2>Gate Verdict</h2><p>{body}</p></section>"


def _ledger_preview_html(strategy_name: str, trades: tuple[Trade, ...]) -> str:
    rows: list[tuple[str, str, str, str, str, str]] = []
    for trade in trades[-20:]:
        rows.append(
            (
                trade.symbol,
                "long" if trade.direction > 0 else "short",
                _format_datetime(trade.open_ts),
                _format_datetime(trade.close_ts),
                _format_ccy(trade.pnl_account_ccy),
                trade.exit_reason,
            )
        )
    return (
        f"<h3>{escape(strategy_name)}</h3>"
        f"{_table_html(['Symbol', 'Side', 'Open', 'Close', 'PnL', 'Exit'], rows)}"
    )


def _table_html(headers: list[str], rows: list[tuple[object, ...]]) -> str:
    head = "".join(f"<th>{escape(str(header))}</th>" for header in headers)
    body_rows = []
    for row in rows:
        cells = "".join(f"<td>{escape(str(value))}</td>" for value in row)
        body_rows.append(f"<tr>{cells}</tr>")
    if not body_rows:
        body_rows.append(f"<tr><td colspan=\"{len(headers)}\">No data</td></tr>")
    return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"


def _normalize_cohort_metrics(
    *,
    cohort_metrics_by_strategy: Optional[dict[str, CohortMetrics]],
    cohort_results_by_strategy: Optional[dict[str, list[ChallengeResult]]],
) -> dict[str, CohortMetrics]:
    normalized = dict(cohort_metrics_by_strategy or {})
    if cohort_results_by_strategy:
        for strategy_name, strategy_results in cohort_results_by_strategy.items():
            normalized.setdefault(strategy_name, cohort_metrics(strategy_results))
    return normalized


def _default_run_id(results: dict[str, ChallengeResult]) -> str:
    joined = "_".join(strategy.lower().replace(" ", "_") for strategy in results)
    return f"{_utc_now_naive():%Y%m%d_%H%M%S}_{joined}"


def _utc_now_naive() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


def _fig_to_data_uri(fig: Figure) -> str:
    buffer = BytesIO()
    fig.savefig(buffer, format="png", dpi=100, bbox_inches="tight")
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def _format_pct(value: float) -> str:
    if pd.isna(value):
        return "nan"
    if value == float("inf"):
        return "inf"
    return f"{value * 100:.1f}%"


def _format_ratio(value: float) -> str:
    if pd.isna(value):
        return "nan"
    if value == float("inf"):
        return "inf"
    return f"{value:.4f}"


def _format_ccy(value: float) -> str:
    if pd.isna(value):
        return "nan"
    return f"{value:,.2f}"


def _format_datetime(value: datetime) -> str:
    return value.strftime("%Y-%m-%d %H:%M:%S")


_STYLE = """
body {
  margin: 0;
  font-family: Georgia, "Times New Roman", serif;
  background: linear-gradient(180deg, #f4efe6 0%, #fffdf8 100%);
  color: #1f2933;
}
.page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 32px 24px 48px;
}
header {
  padding: 24px;
  border: 1px solid #d6c7b1;
  background: linear-gradient(135deg, #fffdf8 0%, #efe2cc 100%);
  box-shadow: 0 10px 30px rgba(31, 41, 51, 0.08);
}
section {
  margin-top: 28px;
  padding: 20px;
  border: 1px solid #d6c7b1;
  background: rgba(255, 255, 255, 0.92);
}
h1, h2, h3 {
  margin-top: 0;
  color: #7c2d12;
}
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}
.card {
  border: 1px solid #d6c7b1;
  background: #fffaf2;
  padding: 16px;
}
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 12px;
}
th, td {
  border: 1px solid #e5dccd;
  padding: 8px 10px;
  text-align: left;
  font-size: 14px;
}
th {
  background: #f2e6d5;
}
tbody tr:nth-child(even) {
  background: #fcf8f2;
}
img {
  width: 100%;
  height: auto;
  border: 1px solid #d6c7b1;
  background: #ffffff;
}
@media (max-width: 720px) {
  .page {
    padding: 20px 12px 36px;
  }
  section, header {
    padding: 16px;
  }
  th, td {
    font-size: 12px;
  }
}
"""
